### ISSUE TITLE
Continuous release files don't have the correct names

### ISSUE THREAD

**Issue by Clue88** [sugarlabs/musicblocks-launcher#16]
For example, one of the released binaries is called `Musicblocks-3.5.1-arm64.AppImage` when it should be `Musicblocks-continuous-arm64.AppImage`.

**Comment by Clue88** [comment]
Seems like this is the root of the issue.

```
Uploading release artifacts
  Uploading: Musicblocks-continuous-x86_64.dmg/Musicblocks-3.5.1.dmg
  Uploading: Musicblocks-continuous-x86_64.exe/Musicblocks Setup 3.5.1.exe
  Uploading: Musicblocks-continuous-x86_64.snap/Musicblocks_3.5.1_amd64.snap
  Uploading: Musicblocks-continuous-x86_64.AppImage/Musicblocks-x86_64.AppImage
  Uploading: Musicblocks-continuous-aarch64.AppImage/Musicblocks-3.5.1-arm64.AppImage
  Uploading: Musicblocks-continuous-arm.AppImage/Musicblocks-3.5.1-arm64.AppImage
  Problem uploading Musicblocks-continuous-arm.AppImage/Musicblocks-3.5.1-arm64.AppImage as a release asset (request to https://uploads.github.com/repos/sugarlabs/musicblocks-launcher/releases/45074520/assets?name=Musicblocks-3.5.1-arm64.AppImage& failed, reason: socket hang up). Will retry with the md5 hash appended to the filename.
  Uploading: Musicblocks-continuous-x86_64.deb/Musicblocks_3.5.1_amd64.deb
  Uploading: Musicblocks-continuous-x86_64.rpm/Musicblocks-3.5.1.x86_64.rpm
```

**Comment by srevinsaju** [comment]
> Musicblocks-continuous-x86_64.dmg/Musicblocks-3.5.1.dmg

Basically, `Musicblocks-continuous-x86_64.dmg` is the name of the folder, and `Musicblocks-3.5.1.dmg` is the file which is inside the the folder. 
The script tries to fetch the version of musicblocks from the git repository and and adds it into the filename. Should we change it, or let it stay the same?

**Comment by Clue88** [comment]
That's fine with me – the only part that was confusing to me was why one of the files had an md5 hash appended to it. Theoretically this is okay (I just need some place to point Flatpak manifests, etc. to) but it would be better I think if they could keep the directory names so we have more control.

**Comment by srevinsaju** [comment]
I think, we can get it to be `continuous` if we change the `.version` key in `package.json` to `continuous`.

**Comment by Clue88** [comment]
Could we rename the binaries in the CI script? There are two arm-based binaries that should create files with `aarch64` and `arm` but electron-builder uses `arm64` and `armv7l` to refer to the same archs... perhaps that's why there's a name collision/file-not-found? Though that might be fixed with the most recent PR: we would need to see how it outputs into the release.

**Comment by srevinsaju** [comment]
> Could we rename the binaries in the CI script

Its is possible, I think its easy.

> Though that might be fixed with the most recent PR: we would need to see how it outputs into the release.

Right now, the release system is completely broken :sweat_smile:

**Comment by Clue88** [comment]
> Right now, the release system is completely broken 😅

Oh dear. I think the naming issues are somewhat low-priority at the moment – a manifest that uses the binaries can just point to whatever file ends up in the release.

**Comment by Clue88** [comment]
That said if we can rename the binaries that would probably improve maintainability.

The other naming-related issue that I saw was regarding the name "Music Blocks" itself – I believe that the convention that was started is to use `Music Blocks` or `MusicBlocks` over `Musicblocks`. Not urgent but probably best to be consistent.

**Comment by srevinsaju** [comment]
Ok, the release workflow has been tested now. Check out a sample release https://github.com/srevinsaju/musicblocks-launcher/releases

If its okay, we can merge #18 

We can then work on changing the name in a subsequent PR
